package dao.rolePermission;

import entity.rolePermission.RolePermissionExample;
import entity.rolePermission.RolePermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int insert(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int insertSelective(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    List<RolePermissionKey> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);
}